import {Dimensions, StyleSheet} from 'react-native';

export const AddCollectionListStyle = (AppTheme: any) =>
  StyleSheet.create({
    viewCollectionMain: {
      flex: 1,
      backgroundColor: '#fff',
      marginStart: 20,
      marginEnd: 20,
      marginTop: 20,
      overflow: 'hidden',
    },
    editCollectionContainer: {
      minHeight: 100,
      borderRadius: 15,
      backgroundColor: '#F4F4F4',
      borderWidth: 1,
      borderColor: '#FFF',
      marginBottom: 20,
    },
    collectionTextContainerOfAddItem: {
      marginStart: 18,
      marginEnd: 18,
      marginTop: 30,
      marginBottom: 11,
      flexDirection: 'row',
    },
    locationImage: {
      height: 18,
      width: 18,
      resizeMode: 'contain',
      alignItems: 'center',
    },
    collectionText: {
      fontSize: 14,
      fontWeight: '600',
      fontFamily: AppTheme.fonts.Inter,
      marginLeft: 4,
      color: '#141F42',
      width: 83,
    },
    inputContainer2: {
      height: 70,
      borderWidth: 1,
      borderColor: '#C6C9D7',
      borderRadius: 5,
      backgroundColor: '#fff',
      width: Dimensions.get('window').width / 2,
      padding: 9,
      fontSize: 12,
      color: '#727582',
    },
    error: {
      marginTop: 6,
      fontSize: 13,
      fontWeight: '600',
      color: AppTheme.colors.red,
      marginStart: 16,
      fontFamily: AppTheme.fonts.Inter,
    },
    collectionTextContainerOfAddItem2: {
      marginStart: 18,
      marginEnd: 18,
      marginTop: 20,
      marginBottom: 11,
      flexDirection: 'row',
    },
    audioContainer: {
      height: 31,
      flexDirection: 'row',
      borderWidth: 1,
      borderRadius: 5,
      borderColor: '#fff',
      backgroundColor: '#fff',
      alignItems: 'center',
      padding: 8,
      marginTop: 6,
      width: 80,
    },
    voiceButtonText: {
      color: '#0F48FF',
    },
    audioImage: {height: 14, width: 14},

    audioText: {
      fontSize: 13,
      fontFamily: AppTheme.fonts.Inter,
      fontWeight: '500',
      color: '#727582',
      lineHeight: 16,
    },
    inputContainer: {marginTop: -12},
    customButtonWithIcon: {
      height: 20,
      width: 20,
      resizeMode: 'contain',
      borderRadius: 20 / 2,
      marginRight: 5,
    },
    bottomTabHome: {
      alignSelf: 'flex-end',
    },
    commonButtonWithIconContainer: {alignItems: 'center', marginBottom: 10},
  });
